-- +goose Up
ALTER TABLE users 
ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;

-- +goose Down
ALTER TABLE users 
DROP COLUMN created_at,
DROP COLUMN updated_at,
DROP COLUMN deleted_at;